; Original campaign terrain and forces; cooperative starts only.
[BASIC]
LosePicture=LOSTBILD.WSA
WinPicture=WIN1.WSA
BriefPicture=PALACE.WSA
TimeOut=0
MapScale=0
CursorPos=666
TacticalPos=340
LoseFlags=1
WinFlags=3
TechLevel=8

[MAP]
Field=2746,3482,3791
Seed=604

[Player1]
Quota=0
Credits=2000
Brain=Team 1
MaxUnit=25

[Player4]
Quota=0
Credits=1000
Brain=Team 2
MaxUnit=25

[Player3]
Quota=0
Credits=1000
Brain=Team 2
MaxUnit=25

[CHOAM]
Trike=5
Quad=5
Tank=5
Siege Tank=4
Launcher=4
Harvester=2
MCV=2
Carryall=2
Thopter=3

[TEAMS]
1=Player3,Kamikaze,Foot,4,6
2=Player3,Kamikaze,Track,4,6
3=Player3,Normal,Track,5,7
4=Player3,Normal,Wheel,4,6
5=Player4,Normal,Foot,4,6
6=Player4,Kamikaze,Wheel,5,7
7=Player4,Kamikaze,Track,6,8
8=Player4,Normal,Track,5,7

[UNITS]
ID041=Player4,Launcher,256,3470,64,Area Guard
ID040=Player4,Siege Tank,256,3111,64,Area Guard
ID038=Player4,Siege Tank,256,3079,64,Area Guard
ID037=Player4,Launcher,256,3092,64,Area Guard
ID034=Player4,Launcher,256,3042,64,Guard
ID029=Player4,Launcher,256,2986,64,Guard
ID032=Player4,Special,256,2851,64,Area Guard
ID039=Player4,Special,256,2772,64,Ambush
ID030=Player4,Special,256,2729,64,Ambush
ID028=Player4,Siege Tank,256,2726,64,Area Guard
ID035=Player4,Launcher,256,2594,64,Ambush
ID031=Player4,Launcher,256,2583,64,Area Guard
ID043=Player3,Special,256,2543,64,Area Guard
ID033=Player4,Siege Tank,256,2521,64,Area Guard
ID036=Player4,Siege Tank,256,2467,64,Ambush
ID047=Player3,Siege Tank,256,2362,64,Area Guard
ID048=Player3,Siege Tank,256,2225,64,Area Guard
ID045=Player3,Siege Tank,256,1904,64,Ambush
ID042=Player3,Special,256,1915,64,Area Guard
ID024=CoopWildlife,Sandworm,256,1890,64,Ambush
ID046=Player3,Special,256,1777,64,Ambush
ID044=Player3,Siege Tank,256,1786,64,Area Guard
ID025=CoopWildlife,Sandworm,256,972,64,Ambush
ID054=Player1,Quad,256,794,64,Guard
ID052=Player1,Launcher,256,796,64,Guard
ID050=Player1,Siege Tank,256,728,64,Guard
ID053=Player1,Special,256,669,64,Guard
ID066=Player1,Tank,256,599,64,Guard
ID051=Player1,Launcher,256,537,64,Guard
ID049=Player1,Siege Tank,256,540,64,Guard
IDCOOPMCV=Player2,MCV,256,538,64,Guard
IDCOOP054=Player2,Quad,256,601,64,Guard
IDCOOP052=Player2,Launcher,256,473,64,Guard
IDCOOP050=Player2,Siege Tank,256,474,64,Guard
IDCOOP053=Player2,Special,256,475,64,Guard
IDCOOP066=Player2,Tank,256,665,64,Guard
IDCOOP051=Player2,Launcher,256,536,64,Guard
IDCOOP049=Player2,Siege Tank,256,600,64,Guard

[STRUCTURES]
GEN2099=Player3,Wall
GEN2100=Player3,Wall
GEN2101=Player3,Wall
GEN2102=Player3,Wall
GEN2107=Player3,Wall
GEN2108=Player3,Wall
GEN2109=Player3,Wall
GEN2163=Player3,Wall
GEN2166=Player3,Wall
GEN2171=Player3,Wall
GEN2225=Player3,Concrete
GEN2226=Player3,Wall
GEN2227=Player3,Wall
GEN2230=Player3,Wall
GEN2231=Player3,Wall
GEN2233=Player3,Concrete
GEN2234=Player3,Concrete
GEN2235=Player3,Wall
GEN2238=Player3,Wall
GEN2239=Player3,Wall
GEN2288=Player3,Concrete
GEN2289=Player3,Concrete
GEN2290=Player3,Concrete
GEN2291=Player3,Concrete
GEN2292=Player3,Concrete
GEN2293=Player3,Concrete
GEN2294=Player3,Concrete
GEN2295=Player3,Concrete
GEN2296=Player3,Concrete
GEN2297=Player3,Concrete
GEN2298=Player3,Concrete
GEN2299=Player3,Wall
GEN2302=Player3,Concrete
GEN2351=Player3,Wall
GEN2352=Player3,Concrete
GEN2355=Player3,Concrete
GEN2356=Player3,Concrete
GEN2360=Player3,Concrete
GEN2361=Player3,Concrete
GEN2362=Player3,Concrete
GEN2363=Player3,Wall
GEN2366=Player3,Concrete
GEN2415=Player3,Wall
GEN2416=Player3,Concrete
GEN2419=Player3,Concrete
GEN2420=Player3,Concrete
GEN2424=Player3,Concrete
GEN2427=Player3,Wall
GEN2428=Player3,Wall
GEN2479=Player3,Wall
GEN2480=Player3,Wall
GEN2481=Player3,Wall
GEN2482=Player3,Wall
GEN2483=Player3,Wall
GEN2484=Player3,Wall
GEN2488=Player3,Concrete
GEN2544=Player3,Wall
GEN2548=Player3,Wall
GEN2608=Player3,Wall
GEN2612=Player3,Wall
GEN2613=Player3,Concrete
GEN2614=Player3,Concrete
GEN2672=Player3,Wall
GEN2673=Player3,Wall
GEN2674=Player3,Wall
GEN2675=Player3,Wall
GEN2676=Player3,Wall
GEN2677=Player3,Wall
GEN2736=Player3,Wall
GEN2737=Player3,Wall
GEN2741=Player3,Concrete
GEN2801=Player3,Concrete
GEN2805=Player3,Concrete
GEN2844=Player4,Wall
GEN2845=Player4,Wall
GEN2854=Player4,Wall
GEN2855=Player4,Wall
GEN2856=Player4,Wall
GEN2857=Player4,Wall
GEN2858=Player4,Wall
GEN2866=Player3,Concrete
GEN2867=Player3,Concrete
GEN2868=Player3,Concrete
GEN2906=Player4,Concrete
GEN2909=Player4,Wall
GEN2914=Player4,Wall
GEN2915=Player4,Wall
GEN2916=Player4,Wall
GEN2917=Player4,Wall
GEN2918=Player4,Wall
GEN2922=Player4,Wall
GEN2923=Player4,Wall
GEN2931=Player3,Concrete
GEN2932=Player3,Concrete
GEN2933=Player3,Concrete
GEN2965=Player4,Wall
GEN2966=Player4,Wall
GEN2967=Player4,Wall
GEN2968=Player4,Wall
GEN2969=Player4,Concrete
GEN2970=Player4,Concrete
GEN2973=Player4,Wall
GEN2974=Player4,Wall
GEN2975=Player4,Concrete
GEN2976=Player4,Concrete
GEN2977=Player4,Wall
GEN2978=Player4,Wall
GEN2982=Player4,Wall
GEN2986=Player4,Concrete
GEN2996=Player3,Concrete
GEN2998=Player3,Concrete
GEN3029=Player4,Wall
GEN3033=Player4,Concrete
GEN3034=Player4,Concrete
GEN3035=Player4,Concrete
GEN3036=Player4,Concrete
GEN3037=Player4,Concrete
GEN3038=Player4,Concrete
GEN3039=Player4,Concrete
GEN3040=Player4,Concrete
GEN3041=Player4,Wall
GEN3042=Player4,Concrete
GEN3046=Player4,Wall
GEN3047=Player4,Concrete
GEN3048=Player4,Concrete
GEN3049=Player4,Concrete
GEN3060=Player3,Wall
GEN3061=Player3,Wall
GEN3062=Player3,Wall
GEN3063=Player3,Wall
GEN3093=Player4,Wall
GEN3097=Player4,Concrete
GEN3098=Player4,Concrete
GEN3099=Player4,Concrete
GEN3102=Player4,Concrete
GEN3103=Player4,Concrete
GEN3105=Player4,Wall
GEN3106=Player4,Wall
GEN3110=Player4,Wall
GEN3111=Player4,Concrete
GEN3112=Player4,Concrete
GEN3124=Player3,Wall
GEN3127=Player3,Wall
GEN3142=Player4,Wall
GEN3143=Player4,Wall
GEN3144=Player4,Wall
GEN3155=Player4,Wall
GEN3156=Player4,Wall
GEN3157=Player4,Wall
GEN3158=Player4,Concrete
GEN3159=Player4,Concrete
GEN3160=Player4,Concrete
GEN3161=Player4,Concrete
GEN3162=Player4,Concrete
GEN3166=Player4,Concrete
GEN3170=Player4,Wall
GEN3171=Player4,Wall
GEN3172=Player4,Wall
GEN3173=Player4,Wall
GEN3174=Player4,Wall
GEN3188=Player3,Wall
GEN3191=Player3,Wall
GEN3208=Player4,Wall
GEN3217=Player4,Concrete
GEN3221=Player4,Concrete
GEN3229=Player4,Concrete
GEN3230=Player4,Concrete
GEN3236=Player4,Concrete
GEN3252=Player3,Wall
GEN3255=Player3,Wall
GEN3272=Player4,Wall
GEN3273=Player4,Wall
GEN3274=Player4,Wall
GEN3276=Player4,Wall
GEN3277=Player4,Wall
GEN3278=Player4,Wall
GEN3279=Player4,Wall
GEN3280=Player4,Concrete
GEN3281=Player4,Concrete
GEN3285=Player4,Concrete
GEN3293=Player4,Concrete
GEN3316=Player3,Wall
GEN3319=Player3,Wall
GEN3335=Player4,Concrete
GEN3338=Player4,Wall
GEN3339=Player4,Concrete
GEN3340=Player4,Wall
GEN3343=Player4,Wall
GEN3344=Player4,Wall
GEN3345=Player4,Wall
GEN3346=Player4,Wall
GEN3347=Player4,Wall
GEN3348=Player4,Wall
GEN3349=Player4,Wall
GEN3360=Player4,Concrete
GEN3361=Player4,Concrete
GEN3362=Player4,Concrete
GEN3380=Player3,Wall
GEN3381=Player3,Wall
GEN3382=Player3,Wall
GEN3383=Player3,Wall
GEN3399=Player4,Concrete
GEN3402=Player4,Wall
GEN3403=Player4,Concrete
GEN3404=Player4,Wall
GEN3413=Player4,Wall
GEN3463=Player4,Concrete
GEN3466=Player4,Wall
GEN3477=Player4,Wall
GEN3518=Player3,Concrete
GEN3521=Player4,Concrete
GEN3583=Player3,Wall
GEN3584=Player4,Wall
GEN3652=Player4,Wall
GEN3709=Player3,Concrete
GEN3710=Player3,Concrete
GEN3713=Player4,Concrete
GEN3714=Player4,Concrete
GEN3777=Player4,Concrete
ID000=Player1,Const Yard,256,666
ID001=Player3,Heavy Fctry,256,2485
ID002=Player4,Const Yard,256,3294
ID003=Player3,WOR,256,2353
ID004=Player3,Light Fctry,256,2164
ID005=Player3,Hi-Tech,256,2545
ID006=Player3,R-Turret,256,2162
ID007=Player3,R-Turret,256,2036
ID008=Player3,R-Turret,256,2287
ID009=Player3,R-Turret,256,2232
ID010=Player3,Refinery,256,2738
ID011=Player3,Const Yard,256,2425
ID012=Player3,Refinery,256,3580
ID013=Player3,Windtrap,256,2429
ID014=Player3,Windtrap,256,2300
ID015=Player3,Windtrap,256,2172
ID016=Player3,Spice Silo,256,3125
ID017=Player3,Spice Silo,256,3253
ID018=Player3,R-Turret,256,2997
ID019=Player3,R-Turret,256,2044
ID020=Player3,R-Turret,256,2671
ID021=Player4,Heavy Fctry,256,3030
ID022=Player4,WOR,256,2907
ID023=Player4,Light Fctry,256,3100
ID024=Player4,Refinery,256,3218
ID025=Player4,Spice Silo,256,3411
ID026=Player4,Spice Silo,256,3409
ID027=Player4,Refinery,256,3585
ID028=Player4,R-Turret,256,3588
ID029=Player3,Repair,256,2357
ID030=Player4,R-Turret,256,2910
ID031=Player4,Palace,256,2979
ID032=Player4,R-Turret,256,2901
ID033=Player4,R-Turret,256,2843
ID035=Player4,Windtrap,256,3407
ID036=Player4,Repair,256,2919
ID037=Player4,Windtrap,256,3336
ID038=Player4,Windtrap,256,3206
ID039=Player4,R-Turret,256,3154
ID040=Player4,R-Turret,256,3209
ID041=Player4,Hi-Tech,256,3233
ID042=Player4,Windtrap,256,3464
ID043=Player4,R-Turret,256,2853
ID044=Player3,R-Turret,256,3517
ID045=Player4,R-Turret,256,2859
ID046=Player4,Windtrap,256,3341

[REINFORCEMENTS]
1=Player4,Troopers,Enemybase,12
2=Player3,Siege Tank,Enemybase,12
3=Player4,Troopers,Enemybase,14
4=Player4,Special,Enemybase,14
5=Player3,Launcher,Enemybase,21
6=Player3,Special,Enemybase,21
7=Player1,Siege Tank,Homebase,13
8=Player1,Launcher,Homebase,13
9=Player1,Infantry,Homebase,22
10=Player1,Siege Tank,Homebase,22
11=Player1,Special,Homebase,22
12=Player5,Troopers,Enemybase,30+
13=Player5,Troopers,Enemybase,30+
14=Player5,Troopers,Enemybase,30+
15=Player5,Troopers,Enemybase,30+

[Player2]
Quota=0
Credits=2000
Brain=Team 1
MaxUnit=25

[Player5]
Credits=0
Quota=0
MaxUnit=25
Brain=Team 2

[COOP_TEMPLATE]
Schema=1
Stage=8
Mod=Tornie
ParticipantCount=5
SourceFaction=6
OriginalMission=20
SourceHouse=Neutral
SourceFile=mods/Tornie/campaign/scenn020.ini
SourceSha256=a978087b166a712004d34f98acf3826e542c25ed4bc2998d839a1564cc303ec6
SourceHashNormalization=LF
SharedQuota=0
OriginalWinFlags=3
OriginalLoseFlags=1
WildlifeOwner=CoopWildlife
OwnerCorrectionCount=4
OwnerCorrectionHouseCount=1
OwnerCorrection1=Ordos,Player5
EnemyFaction1=7
EnemyPresent1=1
EnemyDeclared1=1
EnemyDeferred1=0
SourceOpponent1=Rebels
EnemyFaction2=10
EnemyPresent2=1
EnemyDeclared2=1
EnemyDeferred2=0
SourceOpponent2=Kleshmersh
EnemyFaction3=1
EnemyPresent3=0
EnemyDeclared3=0
EnemyDeferred3=1
SourceOpponent3=Atreides

