; Original campaign terrain and forces; cooperative starts only.
[BASIC]
LosePicture=LOSTBILD.WSA
WinPicture=WIN1.WSA
BriefPicture=PALACE.WSA
TimeOut=0
MapScale=0
CursorPos=666
TacticalPos=340
LoseFlags=1
WinFlags=3
TechLevel=8

[MAP]
Field=3003
Seed=604

[Player1]
Quota=0
Credits=2000
Brain=Team 1
MaxUnit=25

[Player3]
Quota=0
Credits=1000
Brain=Team 2
MaxUnit=25

[Player4]
Quota=0
Credits=1000
Brain=Team 2
MaxUnit=25

[CHOAM]
Trike=5
Quad=5
Tank=5
Siege Tank=4
Launcher=4
Harvester=2
MCV=2
Carryall=2
Thopter=3

[TEAMS]
1=Player4,Kamikaze,Foot,3,5
2=Player4,Kamikaze,Track,5,7
3=Player4,Normal,Track,5,7
4=Player4,Normal,Wheel,4,6
5=Player3,Normal,Foot,4,6
6=Player3,Kamikaze,Wheel,4,6
7=Player3,Kamikaze,Track,6,8
8=Player3,Normal,Track,5,7

[UNITS]
ID022=Player3,Launcher,256,3470,64,Area Guard
ID024=Player3,Siege Tank,256,3079,64,Ambush
ID023=Player3,Siege Tank,256,3111,64,Area Guard
ID025=Player3,Launcher,256,3042,64,Guard
ID026=Player3,Launcher,256,2986,64,Guard
ID027=Player3,Special,256,2851,64,Ambush
ID028=Player3,Special,256,2772,64,Ambush
ID030=Player3,Siege Tank,256,2726,64,Ambush
ID029=Player3,Special,256,2729,64,Ambush
ID032=Player3,Launcher,256,2583,64,Area Guard
ID031=Player3,Launcher,256,2594,64,Ambush
ID034=Player3,Siege Tank,256,2521,64,Area Guard
ID033=Player4,Special,256,2543,64,Area Guard
ID035=Player3,Siege Tank,256,2467,64,Ambush
ID036=Player4,Siege Tank,256,2362,64,Ambush
ID037=Player4,Siege Tank,256,2225,64,Area Guard
ID039=Player4,Special,256,1915,64,Ambush
ID038=Player4,Siege Tank,256,1904,64,Ambush
ID019=Player3,Sandworm,256,1890,64,Ambush
ID041=Player4,Siege Tank,256,1786,64,Ambush
ID040=Player4,Special,256,1777,64,Ambush
ID020=Player3,Sandworm,256,972,64,Ambush
ID043=Player1,Launcher,256,796,64,Guard
ID042=Player1,Quad,256,794,64,Guard
ID044=Player1,Siege Tank,256,728,64,Guard
ID045=Player1,Special,256,669,64,Guard
ID046=Player1,Tank,256,599,64,Guard
ID048=Player1,Siege Tank,256,540,64,Guard
ID047=Player1,Launcher,256,537,64,Guard
IDCOOPMCV=Player2,MCV,256,538,64,Guard
IDCOOP043=Player2,Launcher,256,601,64,Guard
IDCOOP042=Player2,Quad,256,473,64,Guard
IDCOOP044=Player2,Siege Tank,256,474,64,Guard
IDCOOP045=Player2,Special,256,475,64,Guard
IDCOOP046=Player2,Tank,256,665,64,Guard
IDCOOP048=Player2,Siege Tank,256,536,64,Guard
IDCOOP047=Player2,Launcher,256,600,64,Guard

[STRUCTURES]
GEN3584=Player3,Wall
GEN3583=Player4,Wall
GEN3477=Player3,Wall
GEN3466=Player3,Wall
GEN3463=Player3,Concrete
GEN3413=Player3,Wall
GEN3404=Player3,Wall
GEN3403=Player3,Concrete
GEN3402=Player3,Wall
GEN3399=Player3,Concrete
GEN3384=Player4,Concrete
GEN3383=Player4,Concrete
GEN3362=Player3,Concrete
GEN3361=Player3,Concrete
GEN3360=Player3,Concrete
GEN3349=Player3,Wall
GEN3348=Player3,Wall
GEN3347=Player3,Wall
GEN3346=Player3,Wall
GEN3345=Player3,Wall
GEN3344=Player3,Wall
GEN3343=Player3,Wall
GEN3340=Player3,Wall
GEN3339=Player3,Concrete
GEN3338=Player3,Wall
GEN3335=Player3,Concrete
GEN3320=Player4,Concrete
GEN3319=Player4,Concrete
GEN3293=Player3,Concrete
GEN3285=Player3,Concrete
GEN3281=Player3,Concrete
GEN3280=Player3,Concrete
GEN3279=Player3,Wall
GEN3278=Player3,Wall
GEN3277=Player3,Wall
GEN3276=Player3,Wall
GEN3274=Player3,Wall
GEN3273=Player3,Wall
GEN3272=Player3,Wall
GEN3256=Player4,Concrete
GEN3255=Player4,Concrete
GEN3254=Player4,Concrete
GEN3236=Player3,Concrete
GEN3230=Player3,Concrete
GEN3229=Player3,Concrete
GEN3221=Player3,Concrete
GEN3217=Player3,Concrete
GEN3208=Player3,Wall
GEN3192=Player4,Concrete
GEN3191=Player4,Concrete
GEN3190=Player4,Concrete
GEN3174=Player3,Wall
GEN3173=Player3,Wall
GEN3172=Player3,Wall
GEN3171=Player3,Wall
GEN3170=Player3,Wall
GEN3166=Player3,Concrete
GEN3162=Player3,Concrete
GEN3161=Player3,Concrete
GEN3160=Player3,Concrete
GEN3159=Player3,Concrete
GEN3158=Player3,Concrete
GEN3157=Player3,Concrete
GEN3156=Player3,Wall
GEN3155=Player3,Wall
GEN3144=Player3,Wall
GEN3143=Player3,Wall
GEN3142=Player3,Wall
GEN3127=Player4,Concrete
GEN3126=Player4,Concrete
GEN3112=Player3,Concrete
GEN3111=Player3,Concrete
GEN3110=Player3,Wall
GEN3106=Player3,Wall
GEN3105=Player3,Wall
GEN3103=Player3,Concrete
GEN3102=Player3,Concrete
GEN3099=Player3,Concrete
GEN3098=Player3,Concrete
GEN3097=Player3,Wall
GEN3093=Player3,Concrete
GEN3092=Player3,Concrete
GEN3049=Player3,Concrete
GEN3048=Player3,Concrete
GEN3047=Player3,Concrete
GEN3046=Player3,Wall
GEN3042=Player3,Concrete
GEN3041=Player3,Wall
GEN3040=Player3,Concrete
GEN3039=Player3,Concrete
GEN3038=Player3,Concrete
GEN3037=Player3,Concrete
GEN3036=Player3,Concrete
GEN3035=Player3,Concrete
GEN3034=Player3,Concrete
GEN3033=Player3,Wall
GEN3029=Player3,Concrete
GEN2998=Player4,Concrete
GEN2996=Player4,Concrete
GEN2986=Player3,Concrete
GEN2982=Player3,Wall
GEN2978=Player3,Wall
GEN2977=Player3,Wall
GEN2976=Player3,Concrete
GEN2975=Player3,Concrete
GEN2974=Player3,Wall
GEN2973=Player3,Wall
GEN2970=Player3,Concrete
GEN2969=Player3,Wall
GEN2968=Player3,Wall
GEN2967=Player3,Wall
GEN2966=Player3,Wall
GEN2965=Player3,Wall
GEN2933=Player4,Concrete
GEN2932=Player4,Concrete
GEN2931=Player4,Concrete
GEN2923=Player3,Wall
GEN2922=Player3,Wall
GEN2918=Player3,Wall
GEN2917=Player3,Wall
GEN2916=Player3,Wall
GEN2915=Player3,Wall
GEN2914=Player3,Wall
GEN2909=Player3,Wall
GEN2906=Player3,Concrete
GEN2868=Player4,Concrete
GEN2867=Player4,Concrete
GEN2866=Player4,Concrete
GEN2858=Player3,Wall
GEN2857=Player3,Wall
GEN2856=Player3,Wall
GEN2855=Player3,Wall
GEN2854=Player3,Wall
GEN2845=Player3,Wall
GEN2844=Player3,Wall
GEN2805=Player4,Concrete
GEN2801=Player4,Concrete
GEN2741=Player4,Concrete
GEN2737=Player4,Wall
GEN2736=Player4,Wall
GEN2677=Player4,Wall
GEN2676=Player4,Wall
GEN2675=Player4,Wall
GEN2674=Player4,Wall
GEN2673=Player4,Wall
GEN2672=Player4,Wall
GEN2614=Player4,Concrete
GEN2613=Player4,Concrete
GEN2612=Player4,Wall
GEN2608=Player4,Wall
GEN2548=Player4,Wall
GEN2544=Player4,Wall
GEN2488=Player4,Concrete
GEN2484=Player4,Wall
GEN2483=Player4,Wall
GEN2482=Player4,Wall
GEN2481=Player4,Wall
GEN2480=Player4,Wall
GEN2479=Player4,Wall
GEN2424=Player4,Concrete
GEN2420=Player4,Concrete
GEN2419=Player4,Concrete
GEN2416=Player4,Concrete
GEN2415=Player4,Wall
GEN2366=Player4,Concrete
GEN2362=Player4,Concrete
GEN2361=Player4,Concrete
GEN2360=Player4,Concrete
GEN2356=Player4,Concrete
GEN2355=Player4,Concrete
GEN2352=Player4,Concrete
GEN2351=Player4,Wall
GEN2302=Player4,Concrete
GEN2298=Player4,Concrete
GEN2297=Player4,Concrete
GEN2296=Player4,Concrete
GEN2295=Player4,Concrete
GEN2294=Player4,Concrete
GEN2293=Player4,Concrete
GEN2292=Player4,Concrete
GEN2291=Player4,Concrete
GEN2290=Player4,Concrete
GEN2289=Player4,Concrete
GEN2288=Player4,Concrete
GEN2239=Player4,Wall
GEN2238=Player4,Concrete
GEN2235=Player4,Wall
GEN2234=Player4,Concrete
GEN2233=Player4,Concrete
GEN2231=Player4,Wall
GEN2230=Player4,Wall
GEN2227=Player4,Wall
GEN2226=Player4,Wall
GEN2225=Player4,Concrete
GEN2171=Player4,Wall
GEN2166=Player4,Wall
GEN2163=Player4,Wall
GEN2109=Player4,Wall
GEN2108=Player4,Wall
GEN2107=Player4,Wall
GEN2102=Player4,Wall
GEN2101=Player4,Wall
GEN2100=Player4,Wall
GEN2099=Player4,Wall
ID046=Player3,Heavy Fctry,256,3233
ID045=Player4,R-Turret,256,3321
ID044=Player3,Windtrap,256,3341
ID043=Player3,R-Turret,256,2859
ID042=Player4,R-Turret,256,3062
ID041=Player3,R-Turret,256,2853
ID040=Player3,Windtrap,256,3464
ID039=Player3,R-Turret,256,3154
ID038=Player3,R-Turret,256,3209
ID037=Player3,Windtrap,256,3206
ID036=Player3,Windtrap,256,3336
ID035=Player3,Repair,256,2919
ID034=Player3,Windtrap,256,3407
ID033=Player4,R-Turret,256,2997
ID032=Player3,R-Turret,256,2843
ID031=Player3,R-Turret,256,2901
ID030=Player3,Palace,256,2979
ID029=Player3,R-Turret,256,2910
ID028=Player4,Repair,256,2357
ID027=Player3,R-Turret,256,3588
ID026=Player3,Refinery,256,3585
ID025=Player3,Spice Silo,256,3409
ID024=Player3,Spice Silo,256,3411
ID023=Player3,Refinery,256,3218
ID022=Player3,Light Fctry,256,3100
ID021=Player3,Barracks,256,2907
ID020=Player3,Heavy Fctry,256,3030
ID019=Player4,R-Turret,256,2671
ID018=Player4,R-Turret,256,2044
ID017=Player4,Spice Silo,256,3060
ID016=Player4,Spice Silo,256,3188
ID015=Player4,Refinery,256,3316
ID014=Player4,Windtrap,256,2172
ID013=Player4,Windtrap,256,2300
ID012=Player4,Windtrap,256,2429
ID011=Player4,Const Yard,256,2425
ID010=Player4,Refinery,256,2738
ID009=Player4,R-Turret,256,2232
ID008=Player4,R-Turret,256,2287
ID007=Player4,R-Turret,256,2036
ID006=Player4,R-Turret,256,2162
ID005=Player4,Hi-Tech,256,2545
ID004=Player4,Light Fctry,256,2164
ID003=Player4,WOR,256,2353
ID002=Player3,Const Yard,256,3294
ID001=Player4,Heavy Fctry,256,2485
ID000=Player1,Const Yard,256,666

[REINFORCEMENTS]
1=Player3,Troopers,Enemybase,12
2=Player3,Siege Tank,Enemybase,12
3=Player3,Troopers,Enemybase,14
4=Player3,Special,Enemybase,14
5=Player4,Troopers,Enemybase,21
6=Player4,Special,Enemybase,21
7=Player1,Siege Tank,Homebase,13
8=Player1,Launcher,Homebase,13
9=Player1,Infantry,Homebase,22
10=Player1,Siege Tank,Homebase,22
11=Player1,Special,Homebase,22
12=Player3,Troopers,Enemybase,30+
13=Player3,Troopers,Enemybase,30+
14=Player3,Troopers,Enemybase,30+
15=Player3,Troopers,Enemybase,30+

[Player2]
Quota=0
Credits=2000
Brain=Team 1
MaxUnit=25

[Player5]
Credits=0
Quota=0
MaxUnit=25
Brain=Team 2

[COOP_TEMPLATE]
Schema=1
Stage=8
Mod=Tornie
ParticipantCount=5
SourceFaction=7
OriginalMission=20
SourceHouse=Rebels
SourceFile=mods/Tornie/campaign/scenr020.ini
SourceSha256=e953ea1225a954f3795b0b2d47e56a1a18ca5720ac3774dbb93d817f25864dac
SourceHashNormalization=LF
SharedQuota=0
OriginalWinFlags=3
OriginalLoseFlags=1
OwnerCorrectionCount=0
OwnerCorrectionHouseCount=0
EnemyFaction1=8
EnemyPresent1=1
EnemyDeclared1=1
EnemyDeferred1=0
SourceOpponent1=Corruptique
EnemyFaction2=11
EnemyPresent2=1
EnemyDeclared2=1
EnemyDeferred2=0
SourceOpponent2=Tharpique
EnemyFaction3=-1
EnemyPresent3=0
EnemyDeclared3=0
EnemyDeferred3=0
SourceOpponent3=Ordos

