; Original campaign terrain and forces; cooperative starts only.
[BASIC]
LosePicture=LOSTBILD.WSA
WinPicture=WIN2.WSA
BriefPicture=SARDUKAR.WSA
TimeOut=0
TechLevel=9
MapScale=0
CursorPos=3422
TacticalPos=3095
LoseFlags=1
WinFlags=3

[MAP]
Bloom=983,1762,2015,3343,3383
Field=83,130,156,177,231,381,567
Seed=392

[Player4]
Quota=0
Credits=1500
Brain=Team 2
MaxUnit=20

[Player1]
Quota=2500
Credits=1000
Brain=Team 1
MaxUnit=25

[Player3]
Quota=0
Credits=1500
Brain=Team 2
MaxUnit=20

[Player5]
Quota=0
Credits=2500
Brain=Team 2
MaxUnit=20

[CHOAM]
Trike=5
Quad=5
Tank=6
Launcher=5
Siege Tank=6
Harvester=4
MCV=2
Thopter=5
Carryall=2

[TEAMS]
1=Player3,Kamikaze,Foot,4,6
2=Player3,Kamikaze,Track,4,6
3=Player3,Normal,Track,4,6
4=Player3,Kamikaze,Wheel,3,5
5=Player4,Normal,Foot,3,5
6=Player4,Kamikaze,Wheel,4,6
7=Player4,Kamikaze,Track,5,7
8=Player4,Normal,Track,4,6
9=Player5,Kamikaze,Foot,4,6
10=Player5,Normal,Foot,3,5
11=Player5,Kamikaze,Foot,4,6
12=Player5,Kamikaze,Track,4,6
13=Player5,Normal,Track,3,5

[UNITS]
ID022=Player1,Special,256,3679,64,Guard
ID023=Player1,Siege Tank,256,3612,64,Guard
ID024=Player1,Siege Tank,256,3553,64,Guard
ID025=Player1,Siege Tank,256,3356,64,Guard
ID027=Player1,Special,256,3294,64,Guard
ID026=Player1,Siege Tank,256,3296,64,Guard
ID019=Player5,Sandworm,256,2515,64,Ambush
ID020=Player5,Sandworm,256,1951,64,Ambush
ID028=Player3,Special,256,1406,64,Guard
ID029=Player3,Siege Tank,256,1209,64,Area Guard
ID030=Player3,Siege Tank,256,1014,64,Area Guard
ID031=Player4,Special,256,849,64,Area Guard
ID034=Player5,Siege Tank,256,814,64,Area Guard
ID033=Player3,Siege Tank,256,821,64,Area Guard
ID032=Player4,Special,256,795,64,Area Guard
ID035=Player3,Special,256,698,64,Area Guard
ID037=Player4,Launcher,256,531,64,Area Guard
ID036=Player4,Launcher,256,533,64,Area Guard
ID039=Player4,Special,256,457,64,Area Guard
ID038=Player5,Launcher,256,482,64,Area Guard
ID041=Player5,Launcher,256,352,64,Area Guard
ID040=Player5,Launcher,256,356,64,Area Guard
IDCOOPMCV=Player2,MCV,256,3420,64,Guard
IDCOOP022=Player2,Special,256,3357,64,Guard
IDCOOP023=Player2,Siege Tank,256,3355,64,Guard
IDCOOP024=Player2,Siege Tank,256,3419,64,Guard
IDCOOP025=Player2,Siege Tank,256,3483,64,Guard
IDCOOP027=Player2,Special,256,3358,64,Guard
IDCOOP026=Player2,Siege Tank,256,3292,64,Guard

[STRUCTURES]
GEN1589=Player3,Concrete
GEN1525=Player3,Concrete
GEN1524=Player3,Concrete
GEN1461=Player3,Concrete
GEN1395=Player3,Wall
GEN1343=Player3,Wall
GEN1342=Player3,Wall
GEN1341=Player3,Wall
GEN1340=Player3,Wall
GEN1331=Player3,Wall
GEN1279=Player3,Wall
GEN1276=Player3,Wall
GEN1267=Player3,Wall
GEN1215=Player3,Wall
GEN1212=Player3,Wall
GEN1203=Player3,Wall
GEN1151=Player3,Wall
GEN1150=Player3,Concrete
GEN1149=Player3,Concrete
GEN1148=Player3,Concrete
GEN1147=Player3,Concrete
GEN1106=Player4,Wall
GEN1105=Player4,Wall
GEN1087=Player3,Wall
GEN1083=Player3,Wall
GEN1074=Player3,Concrete
GEN1073=Player3,Concrete
GEN1042=Player4,Wall
GEN1023=Player3,Wall
GEN1019=Player3,Wall
GEN1012=Player3,Concrete
GEN1008=Player3,Concrete
GEN978=Player4,Wall
GEN959=Player3,Wall
GEN958=Player3,Wall
GEN957=Player3,Wall
GEN956=Player3,Wall
GEN955=Player3,Wall
GEN954=Player3,Wall
GEN953=Player3,Wall
GEN948=Player3,Concrete
GEN944=Player3,Concrete
GEN914=Player4,Wall
GEN913=Player4,Concrete
GEN894=Player3,Concrete
GEN880=Player3,Concrete
GEN850=Player4,Concrete
GEN830=Player3,Concrete
GEN817=Player3,Concrete
GEN786=Player4,Concrete
GEN766=Player3,Concrete
GEN765=Player3,Wall
GEN764=Player3,Wall
GEN763=Player3,Wall
GEN762=Player3,Wall
GEN761=Player3,Wall
GEN722=Player4,Concrete
GEN721=Player4,Concrete
GEN702=Player3,Concrete
GEN688=Player5,Wall
GEN687=Player5,Wall
GEN686=Player5,Wall
GEN665=Player4,Wall
GEN664=Player4,Wall
GEN663=Player4,Wall
GEN662=Player4,Wall
GEN658=Player4,Wall
GEN657=Player4,Wall
GEN656=Player4,Wall
GEN655=Player4,Wall
GEN638=Player3,Concrete
GEN625=Player5,Concrete
GEN622=Player5,Wall
GEN611=Player5,Wall
GEN610=Player5,Wall
GEN609=Player5,Wall
GEN601=Player4,Wall
GEN598=Player4,Wall
GEN597=Player4,Wall
GEN596=Player4,Wall
GEN595=Player4,Wall
GEN594=Player4,Wall
GEN591=Player4,Concrete
GEN574=Player3,Concrete
GEN561=Player5,Concrete
GEN558=Player5,Wall
GEN552=Player5,Wall
GEN551=Player5,Wall
GEN550=Player5,Concrete
GEN548=Player5,Wall
GEN547=Player5,Wall
GEN546=Player5,Wall
GEN545=Player5,Wall
GEN544=Player5,Wall
GEN537=Player4,Wall
GEN534=Player4,Wall
GEN533=Player4,Concrete
GEN532=Player4,Wall
GEN531=Player4,Concrete
GEN530=Player4,Wall
GEN527=Player4,Concrete
GEN497=Player5,Concrete
GEN496=Player5,Concrete
GEN495=Player5,Concrete
GEN494=Player5,Concrete
GEN486=Player5,Concrete
GEN485=Player5,Wall
GEN484=Player5,Wall
GEN483=Player5,Wall
GEN482=Player5,Concrete
GEN481=Player5,Wall
GEN480=Player5,Wall
GEN479=Player5,Wall
GEN473=Player4,Wall
GEN472=Player4,Concrete
GEN434=Player5,Concrete
GEN433=Player5,Concrete
GEN432=Player5,Concrete
GEN431=Player5,Concrete
GEN430=Player5,Concrete
GEN429=Player5,Concrete
GEN428=Player5,Concrete
GEN422=Player5,Concrete
GEN421=Player5,Wall
GEN420=Player5,Wall
GEN416=Player5,Wall
GEN415=Player5,Wall
GEN372=Player5,Concrete
GEN371=Player5,Concrete
GEN370=Player5,Concrete
GEN366=Player5,Wall
GEN365=Player5,Wall
GEN364=Player5,Wall
GEN363=Player5,Wall
GEN362=Player5,Wall
GEN358=Player5,Concrete
GEN357=Player5,Wall
GEN356=Player5,Concrete
GEN352=Player5,Concrete
GEN351=Player5,Wall
GEN342=Player4,Concrete
GEN341=Player4,Concrete
GEN334=Player4,Wall
GEN333=Player4,Wall
GEN332=Player4,Wall
GEN331=Player4,Wall
GEN330=Player4,Wall
GEN329=Player4,Wall
GEN328=Player4,Wall
GEN327=Player4,Wall
GEN326=Player4,Wall
GEN314=Player5,Wall
GEN313=Player5,Wall
GEN312=Player5,Wall
GEN311=Player5,Wall
GEN310=Player5,Wall
GEN309=Player5,Wall
GEN308=Player5,Wall
GEN302=Player5,Concrete
GEN298=Player5,Concrete
GEN293=Player5,Wall
GEN292=Player5,Wall
GEN288=Player5,Wall
GEN287=Player5,Wall
GEN277=Player4,Concrete
GEN276=Player4,Concrete
GEN275=Player4,Concrete
GEN270=Player4,Wall
GEN262=Player4,Wall
GEN251=Player5,Wall
GEN250=Player5,Wall
GEN238=Player5,Concrete
GEN234=Player5,Concrete
GEN228=Player5,Wall
GEN227=Player5,Wall
GEN226=Player5,Wall
GEN225=Player5,Wall
GEN224=Player5,Wall
GEN198=Player4,Wall
GEN197=Player4,Wall
GEN170=Player5,Concrete
GEN165=Player5,Concrete
GEN164=Player5,Concrete
GEN106=Player5,Concrete
GEN101=Player5,Concrete
GEN100=Player5,Concrete
GEN42=Player5,Wall
ID022=Player5,Const Yard,256,122
ID028=Player4,Const Yard,256,73
ID056=Player4,Heavy Fctry,256,405
ID055=Player3,Palace,256,881
ID054=Player3,Refinery,256,1075
ID053=Player4,Windtrap,256,976
ID052=Player4,Turret,256,1169
ID051=Player4,Turret,256,979
ID050=Player4,R-Turret,256,1107
ID049=Player3,R-Turret,256,1018
ID048=Player3,Spice Silo,256,508
ID047=Player3,Refinery,256,635
ID046=Player3,Const Yard,256,1204
ID045=Player3,Light Fctry,256,1332
ID044=Player3,R-Turret,256,1588
ID043=Player3,R-Turret,256,816
ID042=Player3,Hi-Tech,256,827
ID041=Player3,WOR,256,1213
ID040=Player3,R-Turret,256,1405
ID039=Player3,Light Fctry,256,825
ID038=Player3,Heavy Fctry,256,1020
ID037=Player4,R-Turret,256,392
ID036=Player4,R-Turret,256,720
ID035=Player4,R-Turret,256,729
ID034=Player4,Windtrap,256,77
ID033=Player3,R-Turret,256,1072
ID032=Player4,Hi-Tech,256,203
ID031=Player5,Repair,256,425
ID030=Player4,Windtrap,256,199
ID029=Player4,Spice Silo,256,75
ID027=Player4,Refinery,256,70
ID026=Player3,R-Turret,256,1211
ID025=Player4,WOR,256,528
ID024=Player4,Light Fctry,256,535
ID023=Player4,Repair,256,399
ID021=Player4,Palace,256,338
ID020=Player1,Const Yard,256,3422
ID019=Player5,R-Turret,256,307
ID018=Player5,Windtrap,256,184
ID017=Player5,Windtrap,256,182
ID016=Player5,Windtrap,256,180
ID015=Player4,Const Yard,256,201
ID014=Player5,R-Turret,256,229
ID013=Player5,R-Turret,256,223
ID012=Player5,Hi-Tech,256,107
ID011=Player5,Const Yard,256,98
ID010=Player5,Refinery,256,95
ID009=Player5,R-Turret,256,553
ID008=Player5,R-Turret,256,689
ID007=Player5,WOR,256,559
ID006=Player5,WOR,256,423
ID005=Player5,Heavy Fctry,256,235
ID004=Player5,R-Turret,256,549
ID003=Player5,R-Turret,256,612
ID002=Player5,R-Turret,256,608
ID001=Player5,R-Turret,256,543
ID000=Player5,Palace,256,289

[REINFORCEMENTS]
1=Player5,Troopers,Enemybase,12+
2=Player3,Siege Tank,Enemybase,12+
3=Player5,Troopers,Enemybase,14+
4=Player4,Siege Tank,Enemybase,14+
5=Player3,Troopers,Enemybase,21+
6=Player3,Special,Enemybase,21+
7=Player1,Special,Homebase,13
8=Player1,Launcher,Homebase,13
9=Player1,Troopers,Homebase,22
10=Player1,Siege Tank,Homebase,22
11=Player1,Special,Homebase,22
12=Player5,Troopers,Enemybase,30+
13=Player5,Troopers,Enemybase,30+
14=Player5,Troopers,Enemybase,30+
15=Player5,Troopers,Enemybase,30+

[Player2]
Quota=2500
Credits=1000
Brain=Team 1
MaxUnit=25

[COOP_TEMPLATE]
Schema=1
Stage=9
Mod=Jericho
ParticipantCount=5
SourceFaction=5
OriginalMission=22
SourceHouse=Mercenary
SourceFile=mods/Jericho/campaign/scenm022.ini
SourceSha256=8f76318734cfcbf61a5fee850f828520ac9d81ab46808fde4d932290cf7b53c4
SourceHashNormalization=LF
SharedQuota=0
OriginalWinFlags=3
OriginalLoseFlags=1
OwnerCorrectionCount=0
OwnerCorrectionHouseCount=0
EnemyFaction1=10
EnemyPresent1=1
EnemyDeclared1=1
EnemyDeferred1=0
SourceOpponent1=Rebels
EnemyFaction2=7
EnemyPresent2=1
EnemyDeclared2=1
EnemyDeferred2=0
SourceOpponent2=Kleshmersh
EnemyFaction3=2
EnemyPresent3=1
EnemyDeclared3=1
EnemyDeferred3=0
SourceOpponent3=Ordos

