#!/usr/bin/env python3
"""Keep the fallback catalogue identical to the shipped INI, within MSVC literal limits."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
text = (root / 'config/Achievements.ini').read_text(encoding='utf-8-sig')
chunks, current = [], ''
for line in text.splitlines(keepends=True):
    if len((current + line).encode('utf-8')) > 8000:
        chunks.append(current)
        current = ''
    current += line
chunks.append(current)
(root / 'include/Achievements/AchievementDefaults.h').write_text(
    '// Generated by scripts/sync-achievements.py from config/Achievements.ini.\n'
    '#pragma once\nnamespace achievements {\ninline constexpr const char* defaultCatalog=\n'
    + '\n'.join('R"ACHIEVEMENTS(' + chunk + ')ACHIEVEMENTS"' for chunk in chunks)
    + ';\n}\n', encoding='utf-8')
